name: larvixon_frontend
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.9.0
  flutter_bloc: ^9.1.1
  flutter_secure_storage: ^9.2.4
  equatable: ^2.0.7
  flutter_localizations:
    sdk: flutter
  intl: any
  go_router: ^16.1.0
  video_player: ^2.10.0
  google_fonts: ^6.3.1
  url_launcher: ^6.3.2
  skeletonizer: ^2.1.0+1
  fpdart: ^1.1.1
  file_picker: ^10.3.3
  animations: ^2.0.11
  shared_preferences: ^2.5.3
  font_awesome_flutter: ^10.10.0
  flutter_svg: ^2.2.1
  flutter_unity_widget: ^2022.2.0
  mask_text_input_formatter: ^2.9.0
  jwt_decoder: ^2.0.1
  markdown_widget: ^2.3.2+8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  bloc_test: ^10.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.9

flutter:
  uses-material-design: true
  generate: true
  fonts:
    - family: PixelatedElegance
      fonts:
        - asset: fonts/PixelatedEleganceRegular-ovyAA.ttf
  assets:
    - assets/images/logo/
    - assets/images/team/
    - assets/legal/

dependency_overrides:
  flutter_unity_widget:
    path: plugins/flutter_unity_widget-2022.2.1